//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} with same key is already registered in this chat. Registration aborted..
        /// </summary>
        internal static string AddChannel_AlreadyRegistered {
            get {
                return ResourceManager.GetString("AddChannel_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration data is corrupted, channel name or network is missing in chat state. Registration process aborted. Please try again..
        /// </summary>
        internal static string AddChannel_CorruptedState {
            get {
                return ResourceManager.GetString("AddChannel_CorruptedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration data is corrupted, network is missing in chat state. Registration process aborted. Please try again..
        /// </summary>
        internal static string AddChannel_CorruptedStateNetwork {
            get {
                return ResourceManager.GetString("AddChannel_CorruptedStateNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided channel key is the default Meshtastic channel key. Anyone will be able to read your messages. This is not secure. Please reply with `my key is not secure` to confirm that you understand the risks and want to proceed with registering this channel, or type {0} to cancel..
        /// </summary>
        internal static string AddChannel_DefaultKeyWarning_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_DefaultKeyWarning_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm that you understand the risks and want to proceed with registering this channel, please reply with `my key is not secure`.
        ///
        ///Please try again or type {0} to cancel the registration..
        /// </summary>
        internal static string AddChannel_InsecureKeyRepeatConfirm_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_InsecureKeyRepeatConfirm_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel name format: &apos;{0}&apos;. The channel name must be a valid Meshtastic channel name (less than 12 bytes).
        ///
        ///Examples:
        ///• {1} 123 MyChannel ZGeGFyhk&lt;...&gt;3sUOUGyaHqrvU= single
        ///• {1} 123 MyChannel ZGeGFyhk&lt;...&gt;3sUOUGyaHqrvU= multiple
        ///Or use {1} without parameters and I&apos;ll ask for the channel name and key..
        /// </summary>
        internal static string AddChannel_InvalidChannelName {
            get {
                return ResourceManager.GetString("AddChannel_InvalidChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network ID format: &apos;{0}&apos;. The network ID must be a valid integer.
        ///
        ///Examples:
        ///• {1} 123 MyChannel ZGeGFyhk&lt;...&gt;3sUOUGyaHqrvU= single
        ///• {1} 123 MyChannel ZGeGFyhk&lt;...&gt;3sUOUGyaHqrvU= multiple
        ///Or use {1} without parameters and I&apos;ll ask for the network, channel name and key..
        /// </summary>
        internal static string AddChannel_InvalidIdFormat {
            get {
                return ResourceManager.GetString("AddChannel_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel key format: &apos;{0}&apos;. The channel key must be a valid Meshtastic channel key (base64-encoded, 16 or 32 bytes).
        ///
        ///Please try again or type {1} to cancel the registration..
        /// </summary>
        internal static string AddChannel_InvalidKey {
            get {
                return ResourceManager.GetString("AddChannel_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel key format: &apos;{0}&apos;. The channel key must be a valid Meshtastic channel key (base64-encoded, 16 or 32 bytes).
        ///
        ///Examples:
        ///• {1} 123 MyChannel ZGeGFyhk&lt;...&gt;3sUOUGyaHqrvU= single
        ///Or use {1} without parameters and I&apos;ll ask for the channel name and key..
        /// </summary>
        internal static string AddChannel_InvalidKeyFormat {
            get {
                return ResourceManager.GetString("AddChannel_InvalidKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mode &apos;{0}&apos;. Use &apos;single&apos; or &apos;multiple&apos; as the third argument..
        /// </summary>
        internal static string AddChannel_InvalidMode {
            get {
                return ResourceManager.GetString("AddChannel_InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel name format: &apos;{0}&apos;. The channel name must be a valid Meshtastic channel name (less than 12 bytes).
        ///
        ///Please try again or type {1} to cancel the registration..
        /// </summary>
        internal static string AddChannel_InvalidName {
            get {
                return ResourceManager.GetString("AddChannel_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network ID. Please reply with a valid network ID from the list, or {0} to cancel..
        /// </summary>
        internal static string AddChannel_InvalidNetworkId {
            get {
                return ResourceManager.GetString("AddChannel_InvalidNetworkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reply with *single* or *multiple*, or type {0} to cancel..
        /// </summary>
        internal static string AddChannel_InvalidSingleDeviceReply_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_InvalidSingleDeviceReply_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send your Meshtastic channel key (base64-encoded, 16 or 32 bytes)..
        /// </summary>
        internal static string AddChannel_NeedKey {
            get {
                return ResourceManager.GetString("AddChannel_NeedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send your Meshtastic channel name..
        /// </summary>
        internal static string AddChannel_NeedName {
            get {
                return ResourceManager.GetString("AddChannel_NeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reply with the network ID from the list, or {0} to cancel..
        /// </summary>
        internal static string AddChannel_NeedNetworkId {
            get {
                return ResourceManager.GetString("AddChannel_NeedNetworkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this channel used by a single device only?
        ///
        ///• Reply *single* - Optimized routing will be used (works only for single device channels)
        ///• Reply *multiple* - Standard broadcast routing will be used
        ///
        ///Type {0} to cancel..
        /// </summary>
        internal static string AddChannel_NeedSingleDevice_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_NeedSingleDevice_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network ID {0} not found. Please make sure to provide a valid network ID.
        ///
        ///*Available networks:*
        ///{1}
        ///Please reply with valid network ID or type {2} to cancel the registration..
        /// </summary>
        internal static string AddChannel_NetworkNotFound_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_NetworkNotFound_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected network &quot;{0}&quot;.
        ///Please send your Meshtastic channel name..
        /// </summary>
        internal static string AddChannel_NetworkSelected {
            get {
                return ResourceManager.GetString("AddChannel_NetworkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding public, well known channels is not allowed. Registration process aborted. Please try with private channels..
        /// </summary>
        internal static string AddChannel_PublicKeyNotAllowed {
            get {
                return ResourceManager.GetString("AddChannel_PublicKeyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding public, well-known channels is not allowed..
        /// </summary>
        internal static string AddChannel_PublicKeyNotAllowedDirect {
            get {
                return ResourceManager.GetString("AddChannel_PublicKeyNotAllowedDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a network by replying with its ID:
        ///{0}
        ///_If your city is not listed and you are ready to convert your device to a TMesh gateway, please contact the administrator - {1}_
        ///
        ///Type {2} to cancel..
        /// </summary>
        internal static string AddChannel_SelectNetwork_Md1 {
            get {
                return ResourceManager.GetString("AddChannel_SelectNetwork_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} has reached the maximum number of verification codes sent. Please wait at least 1 hour before trying again to add the same channel to any chats. Registration aborted..
        /// </summary>
        internal static string AddChannel_TooManyCodesSent {
            get {
                return ResourceManager.GetString("AddChannel_TooManyCodesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code sent to channel {0}. Please reply with the received code here. The code is valid for 5 minutes..
        /// </summary>
        internal static string AddChannel_VerificationCodeSent {
            get {
                return ResourceManager.GetString("AddChannel_VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} ({1}) is already registered in this chat. Registration aborted..
        /// </summary>
        internal static string AddDevice_AlreadyRegistered {
            get {
                return ResourceManager.GetString("AddDevice_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format: &apos;{0}&apos;. The device ID can be decimal or hex (hex starts with ! or #).
        ///
        ///Examples:
        ///• {1} 123456789
        ///• {1} !75bcd15
        ///• {1} #75bcd15
        ///
        ///Or use {1} without parameters and I&apos;ll ask for the device ID..
        /// </summary>
        internal static string AddDevice_InvalidIdFormat {
            get {
                return ResourceManager.GetString("AddDevice_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID. Please send a valid Meshtastic device ID. The device ID can be decimal or hex (hex starts with ! or #). Send {0} to cancel..
        /// </summary>
        internal static string AddDevice_InvalidIdFormatShort {
            get {
                return ResourceManager.GetString("AddDevice_InvalidIdFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send your Meshtastic device ID. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string AddDevice_NeedId {
            get {
                return ResourceManager.GetString("AddDevice_NeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} has not yet been seen by the {1} node in the Meshtastic network.
        ///1. Check that you are located in supported city (network) with {3} command.
        ///2. Verify that primary channel on your device is configured correctly (see correct channels in {3}).
        ///3. Find node {1} in the node list, open it and click on &apos;Exchange user information&apos;. {1} broadcasts its node info every {2} minutes.
        ///
        ///Registration aborted..
        /// </summary>
        internal static string AddDevice_NotSeenByNode {
            get {
                return ResourceManager.GetString("AddDevice_NotSeenByNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} ({1}) has reached the maximum number of verification codes sent. Please wait at least 1 hour before trying again to add the same device to any chats. Registration aborted..
        /// </summary>
        internal static string AddDevice_TooManyCodesSent {
            get {
                return ResourceManager.GetString("AddDevice_TooManyCodesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code sent to device {0} ({1}). Please reply with the received code here. The code is valid for 5 minutes..
        /// </summary>
        internal static string AddDevice_VerificationCodeSent {
            get {
                return ResourceManager.GetString("AddDevice_VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available networks:.
        /// </summary>
        internal static string AvailableNetworks_Md1 {
            get {
                return ResourceManager.GetString("AvailableNetworks_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel_Md2 {
            get {
                return ResourceManager.GetString("Channel_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string ChannelKeyShort_Md1 {
            get {
                return ResourceManager.GetString("ChannelKeyShort_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm that you understand the privacy risks and want to proceed with registering this channel, please reply with `yes`.
        ///
        ///Please try again or type {0} to cancel..
        /// </summary>
        internal static string ChannelPrivacyConfirm_RepeatPrompt_Md1 {
            get {
                return ResourceManager.GetString("ChannelPrivacyConfirm_RepeatPrompt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is chatting with someone else.
        /// </summary>
        internal static string ChatChannel_ChattingWithOther {
            get {
                return ResourceManager.GetString("ChatChannel_ChattingWithOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a channel name and channel ID to start a chat. You or someone else should register channel first with {0} command to get the ID.
        ///
        ///Examples:
        ///• {1} MyChannel:1
        ///Where &apos;MyChannel&apos; name is Meshtastic channel name and &apos;1&apos; is the channel ID you get from TMesh when registering the channel with {0} command.
        ///If channel is registered or approved in this chat you can start chat with {1} MyChannel, where Name is just filter by name (will match MyChannelX, amychannel).
        /// </summary>
        internal static string ChatChannel_InvalidCommand {
            get {
                return ResourceManager.GetString("ChatChannel_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple channels match the provided filter &apos;{0}&apos;. Please be more specific or provide channel ID to start chat..
        /// </summary>
        internal static string ChatChannel_MultipleMatch {
            get {
                return ResourceManager.GetString("ChatChannel_MultipleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no channels with ID {0} and name {1}. The channel needs to be registered first with {2} command to get ID..
        /// </summary>
        internal static string ChatChannel_NotFound {
            get {
                return ResourceManager.GetString("ChatChannel_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📤 Chat request sent to {0}.
        ///Waiting for the channel to reply with 6 digit numeric code to approve the chat....
        /// </summary>
        internal static string ChatChannel_RequestSent {
            get {
                return ResourceManager.GetString("ChatChannel_RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat request from @{0} (Telegram). Reply with code {1} to accept..
        /// </summary>
        internal static string ChatChannel_RequestText {
            get {
                return ResourceManager.GetString("ChatChannel_RequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Chat with {0} is now active. You can start sending messages.
        ///
        ///All messages you send will be forwarded only to this channel. Use {1} command to end the session..
        /// </summary>
        internal static string ChatChannel_SessionStarted {
            get {
                return ResourceManager.GetString("ChatChannel_SessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of chat requests ({0}) sent. Please wait at least 1 hour before trying again to start a chat with any device or channel. Chat request aborted..
        /// </summary>
        internal static string ChatChannel_TooManyRequests {
            get {
                return ResourceManager.GetString("ChatChannel_TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is chatting with someone else.
        /// </summary>
        internal static string ChatDevice_ChattingWithOther {
            get {
                return ResourceManager.GetString("ChatDevice_ChattingWithOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t start a chat with {0} node. This node is used only for relaying messages between devices and Telegram and doesn&apos;t have a user interface to reply to messages. Please use {1} command with the ID of your device or a private channel registered with TMesh to start a chat..
        /// </summary>
        internal static string ChatDevice_IsBotNode {
            get {
                return ResourceManager.GetString("ChatDevice_IsBotNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple devices match the provided filter &apos;{0}&apos;. Please be more specific..
        /// </summary>
        internal static string ChatDevice_MultipleMatch {
            get {
                return ResourceManager.GetString("ChatDevice_MultipleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a device ID or part of the approved/registered device name to start a chat.
        ///
        ///Examples:
        ///• {0} !75bcd15
        ///• {0} MyApprovedNode.
        /// </summary>
        internal static string ChatDevice_NeedArg {
            get {
                return ResourceManager.GetString("ChatDevice_NeedArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid device ID and there are no registered or approved devices in this chat to find device by name. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string ChatDevice_NotValidIdNoDevices {
            get {
                return ResourceManager.GetString("ChatDevice_NotValidIdNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid device ID and does not match any registered or approved device names..
        /// </summary>
        internal static string ChatDevice_NotValidIdNoMatch {
            get {
                return ResourceManager.GetString("ChatDevice_NotValidIdNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📤 Chat request sent to {0} ({1}).
        ///Waiting for the device to reply with 6 digit numeric code to approve the chat....
        /// </summary>
        internal static string ChatDevice_RequestSent {
            get {
                return ResourceManager.GetString("ChatDevice_RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat request from @{0} (Telegram). Reply with code {1} to accept..
        /// </summary>
        internal static string ChatDevice_RequestText {
            get {
                return ResourceManager.GetString("ChatDevice_RequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Chat with {0} ({1}) is now active. You can start sending messages.
        ///
        ///All messages you send will be forwarded only to this device. Use {2} command to end the session..
        /// </summary>
        internal static string ChatDevice_SessionStarted {
            get {
                return ResourceManager.GetString("ChatDevice_SessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of chat requests ({0}) sent. Please wait at least 1 hour before trying again to start a chat with any device. Chat request aborted..
        /// </summary>
        internal static string ChatDevice_TooManyRequests {
            get {
                return ResourceManager.GetString("ChatDevice_TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not known to TMesh. The device needs to broadcast its Node info or send it directly to {1} node using &quot;Exchange user information&quot;..
        /// </summary>
        internal static string ChatDevice_UnknownDevice {
            get {
                return ResourceManager.GetString("ChatDevice_UnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active chat session:.
        /// </summary>
        internal static string ChatStatus_ActiveChatSession_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ActiveChatSession_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved or registered devices and channels still can start new chat sessions\..
        /// </summary>
        internal static string ChatStatus_ApprovedCanStillStartChat_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ApprovedCanStillStartChat_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels approved for chat sessions.
        /// </summary>
        internal static string ChatStatus_ApprovedChannels_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ApprovedChannels_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices approved for chat sessions.
        /// </summary>
        internal static string ChatStatus_ApprovedDevices_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ApprovedDevices_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is *active* in TMesh and can get new chat requests from Meshtastic devices and channels\..
        /// </summary>
        internal static string ChatStatus_ChatActive_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ChatActive_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshtastic command: `{0} {1}` via DM to {2} or private channel registered with TMesh\..
        /// </summary>
        internal static string ChatStatus_ChatCommand_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ChatCommand_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is registered in TMesh with name {0} but currently *disabled* for new chat requests\..
        /// </summary>
        internal static string ChatStatus_ChatDisabled_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ChatDisabled_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is not registered in TMesh and cannot receive chat requests from Meshtastic devices or channels\..
        /// </summary>
        internal static string ChatStatus_ChatNotRegistered_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ChatNotRegistered_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered channels and devices:.
        /// </summary>
        internal static string ChatStatus_FilteredChannelsAndDevices_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_FilteredChannelsAndDevices_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered or approved devices or channels matching filter &apos;{0}&apos;\..
        /// </summary>
        internal static string ChatStatus_NoDevicesMatchFilter_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_NoDevicesMatchFilter_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered devices or channels\. You can register a new device with the {0} command, channel with {1} command, or start a temporary chat with `{2} \!\&lt;deviceId\&gt;`\. Please remove the bot from the group if you don&apos;t need it\..
        /// </summary>
        internal static string ChatStatus_NoRegisteredDevicesOrChannels_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_NoRegisteredDevicesOrChannels_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered channels:.
        /// </summary>
        internal static string ChatStatus_RegisteredChannels_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_RegisteredChannels_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered channels and devices:.
        /// </summary>
        internal static string ChatStatus_RegisteredChannelsAndDevices_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_RegisteredChannelsAndDevices_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered devices:.
        /// </summary>
        internal static string ChatStatus_RegisteredDevices_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_RegisteredDevices_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register this chat in TMesh run command: `{0}`.
        /// </summary>
        internal static string ChatStatus_StartToRegister_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_StartToRegister_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To allow incoming chat request from new Meshtastic devices run command: `{0}`.
        /// </summary>
        internal static string ChatStatus_ToReenableUseStart_Md2 {
            get {
                return ResourceManager.GetString("ChatStatus_ToReenableUseStart_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your city is not listed and you are ready to convert your device to a TMesh gateway, please contact the administrator - {0).
        /// </summary>
        internal static string CityNotListed_Md1 {
            get {
                return ResourceManager.GetString("CityNotListed_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Device {0} ({1}) has been demoted from gateway.
        ///
        ///You can disconnect it from the MQTT server in your Meshtastic app settings..
        /// </summary>
        internal static string DemoteGateway_Done {
            get {
                return ResourceManager.GetString("DemoteGateway_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format: &apos;{0}&apos;. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string DemoteGateway_InvalidIdFormat {
            get {
                return ResourceManager.GetString("DemoteGateway_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format. The device ID can be decimal or hex (hex starts with ! or #). Send {0} to cancel..
        /// </summary>
        internal static string DemoteGateway_InvalidIdOrStop {
            get {
                return ResourceManager.GetString("DemoteGateway_InvalidIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the Meshtastic device ID to demote from gateway. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string DemoteGateway_NeedId {
            get {
                return ResourceManager.GetString("DemoteGateway_NeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a Meshtastic device ID or {0} to cancel..
        /// </summary>
        internal static string DemoteGateway_NeedIdOrStop {
            get {
                return ResourceManager.GetString("DemoteGateway_NeedIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not registered in this chat. You can only demote devices registered in this chat..
        /// </summary>
        internal static string DemoteGateway_NotRegistered {
            get {
                return ResourceManager.GetString("DemoteGateway_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} ({1}) was not registered as a gateway..
        /// </summary>
        internal static string DemoteGateway_WasNotGateway {
            get {
                return ResourceManager.GetString("DemoteGateway_WasNotGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device_Md2 {
            get {
                return ResourceManager.GetString("Device_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices without known position.
        /// </summary>
        internal static string DevicesWithoutKnownPosition {
            get {
                return ResourceManager.GetString("DevicesWithoutKnownPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active chat session was ended.
        /// </summary>
        internal static string Disable_ActiveSessionEnded {
            get {
                return ResourceManager.GetString("Disable_ActiveSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is already disabled. You will not receive requests to start new chat from Meshtastic devices. Devices and channels added via {1} and {2} will still be able to send messages.
        ///
        ///Use {0} to re-enable it..
        /// </summary>
        internal static string Disable_AlreadyDisabled {
            get {
                return ResourceManager.GetString("Disable_AlreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Your chat has been disabled. You will not receive requests to start new chat from Meshtastic devices. Devices and channels added via {1} and {2} will still be able to send messages.
        ///
        ///Use {0} to re-enable it..
        /// </summary>
        internal static string Disable_Done {
            get {
                return ResourceManager.GetString("Disable_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered.
        /// </summary>
        internal static string Filtered_Md2 {
            get {
                return ResourceManager.GetString("Filtered_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash it at.
        /// </summary>
        internal static string FlashFirmwareAt_Md1 {
            get {
                return ResourceManager.GetString("FlashFirmwareAt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        internal static string Gateway_Md2 {
            get {
                return ResourceManager.GetString("Gateway_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateways.
        /// </summary>
        internal static string Gateways_Md1 {
            get {
                return ResourceManager.GetString("Gateways_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Set Device Role to *Client* in Device settings. If you prefer *Client Mute*, than add {0} node to favorites, set device role to *Client* and rebroadcast mode to *KNOWN_ONLY*..
        /// </summary>
        internal static string GatewaySetup_DeviceRole_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_DeviceRole_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Encryption enabled:* On ✅.
        /// </summary>
        internal static string GatewaySetup_EncryptionOn_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_EncryptionOn_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the first packet will be received by the TMesh from your device, you will get a notification in this chat..
        /// </summary>
        internal static string GatewaySetup_FirstSeenNotification_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_FirstSeenNotification_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *JSON output enabled:* Off ❌.
        /// </summary>
        internal static string GatewaySetup_JsonOff_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_JsonOff_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Map reporting:* On ✅.
        /// </summary>
        internal static string GatewaySetup_MapReportingOn_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_MapReportingOn_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📡 *MQTT Gateway Setup Instructions*.
        /// </summary>
        internal static string GatewaySetup_MqttHeader_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_MqttHeader_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your Meshtastic app → Config → Network → MQTT and set the following:.
        /// </summary>
        internal static string GatewaySetup_MqttIntroNoStep_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_MqttIntroNoStep_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other settings:.
        /// </summary>
        internal static string GatewaySetup_OtherSettings_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_OtherSettings_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Password:* `{0}`.
        /// </summary>
        internal static string GatewaySetup_Password_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_Password_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Device *{0}* ({1}) has been promoted to gateway..
        /// </summary>
        internal static string GatewaySetup_PromotedHeader_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_PromotedHeader_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Root topic:* `{0}`.
        /// </summary>
        internal static string GatewaySetup_RootTopic_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_RootTopic_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Server address:* `{0}`.
        /// </summary>
        internal static string GatewaySetup_ServerAddress_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_ServerAddress_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. If you haven&apos;t already, flash the custom TMesh firmware: {0}.
        /// </summary>
        internal static string GatewaySetup_Step1Flasher_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_Step1Flasher_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Open your Meshtastic app → Config → Network → MQTT and set the following:.
        /// </summary>
        internal static string GatewaySetup_Step2MqttIntro_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_Step2MqttIntro_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Enable Device telemetry in Meshtastic settings, this will help to monitor network quality..
        /// </summary>
        internal static string GatewaySetup_TelemetryEnable_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_TelemetryEnable_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • If you have enabled Device telemetry please set Number of Hops in LoRa settings to 7..
        /// </summary>
        internal static string GatewaySetup_TelemetryHops_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_TelemetryHops_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *TLS enabled:* Off ❌.
        /// </summary>
        internal static string GatewaySetup_TlsOff_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_TlsOff_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • *Username:* `{0}`.
        /// </summary>
        internal static string GatewaySetup_Username_Md1 {
            get {
                return ResourceManager.GetString("GatewaySetup_Username_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id_Md1 {
            get {
                return ResourceManager.GetString("Id_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id_Md2 {
            get {
                return ResourceManager.GetString("Id_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to delete this chat from TMesh.
        ///This will delete chat, delete all registered devices and channels, delete approved devices and channels.
        ///If you want to disable new chat requests from unknown devices and channels you can use {1} command instead of {0}.
        ///
        ///To confirm please reply with `yes` or {2} to cancel the operation..
        /// </summary>
        internal static string Kill_ConfirmPrompt_Md1 {
            get {
                return ResourceManager.GetString("Kill_ConfirmPrompt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat has been removed. All registrations and approvals have been removed and the chat will no longer receive any messages from the bot. To start using the bot again use {0} command..
        /// </summary>
        internal static string Kill_Done {
            get {
                return ResourceManager.GetString("Kill_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm that you want to remove this chat, please reply with `yes`.
        ///
        ///Please try again or type {0} to cancel..
        /// </summary>
        internal static string Kill_RepeatConfirmPrompt_Md1 {
            get {
                return ResourceManager.GetString("Kill_RepeatConfirmPrompt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last position update.
        /// </summary>
        internal static string LastPositionUpdate {
            get {
                return ResourceManager.GetString("LastPositionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network.
        /// </summary>
        internal static string Network_Md2 {
            get {
                return ResourceManager.GetString("Network_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active operation to stop it..
        /// </summary>
        internal static string NoActiveOperationToStop {
            get {
                return ResourceManager.GetString("NoActiveOperationToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node info.
        /// </summary>
        internal static string NodeInfo_Md2 {
            get {
                return ResourceManager.GetString("NodeInfo_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No networks configured..
        /// </summary>
        internal static string NoNetworksConfigured {
            get {
                return ResourceManager.GetString("NoNetworksConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public channels.
        /// </summary>
        internal static string NoPublicChannels_Md1 {
            get {
                return ResourceManager.GetString("NoPublicChannels_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered devices matching filter &apos;{0}&apos;.
        /// </summary>
        internal static string NoRegisteredDevices {
            get {
                return ResourceManager.GetString("NoRegisteredDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailableShort_Md2 {
            get {
                return ResourceManager.GetString("NotAvailableShort_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        internal static string Position_Md2 {
            get {
                return ResourceManager.GetString("Position_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm that you have read and understood the privacy notice, please reply with `yes`.
        ///
        ///Please try again or type {0} to cancel..
        /// </summary>
        internal static string PrivacyConfirm_RepeatPrompt_Md1 {
            get {
                return ResourceManager.GetString("PrivacyConfirm_RepeatPrompt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found. Please start over with {0}..
        /// </summary>
        internal static string PromoteGateway_DeviceNotFound {
            get {
                return ResourceManager.GetString("PromoteGateway_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You can flash it at: {0}.
        /// </summary>
        internal static string PromoteGateway_FirmwareConfirmFlasherLine {
            get {
                return ResourceManager.GetString("PromoteGateway_FirmwareConfirmFlasherLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device: *{0}* ({1})
        ///
        ///⚠️ To act as a gateway this device must have custom TMesh firmware installed.{2}
        ///
        ///Have you already flashed the TMesh firmware on this device? Reply &quot;*yes*&quot; to confirm and receive MQTT setup instructions, or {3} to cancel..
        /// </summary>
        internal static string PromoteGateway_FirmwareConfirmPrompt_Md1 {
            get {
                return ResourceManager.GetString("PromoteGateway_FirmwareConfirmPrompt_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///⚠️ This command requires custom TMesh firmware on your device. Flash it first at: {0}.
        /// </summary>
        internal static string PromoteGateway_FirmwareWarning {
            get {
                return ResourceManager.GetString("PromoteGateway_FirmwareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///⚠️ This command requires custom TMesh firmware on your device..
        /// </summary>
        internal static string PromoteGateway_FirmwareWarningNoUrl {
            get {
                return ResourceManager.GetString("PromoteGateway_FirmwareWarningNoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}: {1}.
        /// </summary>
        internal static string PromoteGateway_FlasherLine_Md1 {
            get {
                return ResourceManager.GetString("PromoteGateway_FlasherLine_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format: &apos;{0}&apos;. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string PromoteGateway_InvalidIdFormat {
            get {
                return ResourceManager.GetString("PromoteGateway_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format. The device ID can be decimal or hex (hex starts with ! or #). Send {0} to cancel..
        /// </summary>
        internal static string PromoteGateway_InvalidIdOrStop {
            get {
                return ResourceManager.GetString("PromoteGateway_InvalidIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the Meshtastic device ID to promote to gateway. The device ID can be decimal or hex (hex starts with ! or #).{0}.
        /// </summary>
        internal static string PromoteGateway_NeedId {
            get {
                return ResourceManager.GetString("PromoteGateway_NeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a Meshtastic device ID or {0} to cancel..
        /// </summary>
        internal static string PromoteGateway_NeedIdOrStop {
            get {
                return ResourceManager.GetString("PromoteGateway_NeedIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not registered in this chat. Please add it first using {1}..
        /// </summary>
        internal static string PromoteGateway_NotRegistered {
            get {
                return ResourceManager.GetString("PromoteGateway_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please flash the custom TMesh firmware on your device first.{0}
        ///
        ///Reply &quot;*yes*&quot; once the firmware is installed, or {1} to cancel..
        /// </summary>
        internal static string PromoteGateway_RepeatFirmwareConfirm_Md1 {
            get {
                return ResourceManager.GetString("PromoteGateway_RepeatFirmwareConfirm_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session data lost. Please start over with {0}..
        /// </summary>
        internal static string PromoteGateway_SessionLost {
            get {
                return ResourceManager.GetString("PromoteGateway_SessionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Chat is registered successfully with name {0}. Devices can now send requests to start chat with this group using {3} {1} command via {2} node or private channel registered with TMesh..
        /// </summary>
        internal static string RegisterGroup_Done {
            get {
                return ResourceManager.GetString("RegisterGroup_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name can&apos;t start with &apos;@&apos; character. .
        /// </summary>
        internal static string RegisterGroup_NameInvalidAt {
            get {
                return ResourceManager.GetString("RegisterGroup_NameInvalidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid chat name. .
        /// </summary>
        internal static string RegisterGroup_NameInvalidPrefix {
            get {
                return ResourceManager.GetString("RegisterGroup_NameInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name can&apos;t contain spaces. .
        /// </summary>
        internal static string RegisterGroup_NameInvalidSpaces {
            get {
                return ResourceManager.GetString("RegisterGroup_NameInvalidSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a different name..
        /// </summary>
        internal static string RegisterGroup_NameInvalidSuffix {
            get {
                return ResourceManager.GetString("RegisterGroup_NameInvalidSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name is too long. Maximum length is {0} characters. .
        /// </summary>
        internal static string RegisterGroup_NameInvalidTooLong {
            get {
                return ResourceManager.GetString("RegisterGroup_NameInvalidTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name &apos;{0}&apos; is already taken. Please choose a different name..
        /// </summary>
        internal static string RegisterGroup_NameTaken {
            get {
                return ResourceManager.GetString("RegisterGroup_NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid name for the chat..
        /// </summary>
        internal static string RegisterGroup_NeedValidName {
            get {
                return ResourceManager.GetString("RegisterGroup_NeedValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} has been removed from this chat..
        /// </summary>
        internal static string RemoveChannel_Done {
            get {
                return ResourceManager.GetString("RemoveChannel_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} has been removed from this chat and all other chats where you have registered it. Registration of the channel created by other Telegram users in other chats are not removed..
        /// </summary>
        internal static string RemoveChannel_DoneFromAllWithOthers {
            get {
                return ResourceManager.GetString("RemoveChannel_DoneFromAllWithOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel ID format: &apos;{0}&apos;. The channel ID must be a valid integer.
        ///
        ///Please use remove command without params to see ids of registered channels
        ///Examples:
        ///• {1} 123456789
        ///Or use {1} without parameters and I&apos;ll ask for the channel ID..
        /// </summary>
        internal static string RemoveChannel_InvalidIdFormat {
            get {
                return ResourceManager.GetString("RemoveChannel_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel ID format. The channel ID must be a valid integer. Send {0} to cancel..
        /// </summary>
        internal static string RemoveChannel_InvalidIdOrStop {
            get {
                return ResourceManager.GetString("RemoveChannel_InvalidIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved channels:.
        /// </summary>
        internal static string RemoveChannel_ListApproved {
            get {
                return ResourceManager.GetString("RemoveChannel_ListApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the ID of the channel you want to remove..
        /// </summary>
        internal static string RemoveChannel_ListAskId {
            get {
                return ResourceManager.GetString("RemoveChannel_ListAskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered channels:.
        /// </summary>
        internal static string RemoveChannel_ListRegistered {
            get {
                return ResourceManager.GetString("RemoveChannel_ListRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a Channel ID to remove or {0} to cancel..
        /// </summary>
        internal static string RemoveChannel_NeedIdOrStop {
            get {
                return ResourceManager.GetString("RemoveChannel_NeedIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channels are registered or approved in this chat..
        /// </summary>
        internal static string RemoveChannel_NoChanels {
            get {
                return ResourceManager.GetString("RemoveChannel_NoChanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} is not registered in this chat..
        /// </summary>
        internal static string RemoveChannel_NotRegistered {
            get {
                return ResourceManager.GetString("RemoveChannel_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} is not registered in this chat. To prove that you still have access to the channel please register it first in this chat then retry the command..
        /// </summary>
        internal static string RemoveChannel_NotRegisteredInChatForAll {
            get {
                return ResourceManager.GetString("RemoveChannel_NotRegisteredInChatForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} has been removed from this chat..
        /// </summary>
        internal static string RemoveDevice_Done {
            get {
                return ResourceManager.GetString("RemoveDevice_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} has been removed from all chats..
        /// </summary>
        internal static string RemoveDevice_DoneFromAll {
            get {
                return ResourceManager.GetString("RemoveDevice_DoneFromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format: &apos;{0}&apos;. The device ID can be decimal or hex (hex starts with ! or #).
        ///
        ///Examples:
        ///• {1} 123456789
        ///• {1} !75bcd15
        ///• {1} #75bcd15
        ///
        ///Or use {1} without parameters and I&apos;ll ask for the device ID..
        /// </summary>
        internal static string RemoveDevice_InvalidIdFormat {
            get {
                return ResourceManager.GetString("RemoveDevice_InvalidIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device ID format. The device ID can be decimal or hex (hex starts with ! or #). Send {0} to cancel..
        /// </summary>
        internal static string RemoveDevice_InvalidIdOrStop {
            get {
                return ResourceManager.GetString("RemoveDevice_InvalidIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send your Meshtastic device ID. The device ID can be decimal or hex (hex starts with ! or #)..
        /// </summary>
        internal static string RemoveDevice_NeedId {
            get {
                return ResourceManager.GetString("RemoveDevice_NeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a Meshtastic device ID to remove or {0} to cancel..
        /// </summary>
        internal static string RemoveDevice_NeedIdOrStop {
            get {
                return ResourceManager.GetString("RemoveDevice_NeedIdOrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not registered in this chat..
        /// </summary>
        internal static string RemoveDevice_NotRegistered {
            get {
                return ResourceManager.GetString("RemoveDevice_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not registered in this chat. To prove ownership of device please register it first in this chat then retry the command..
        /// </summary>
        internal static string RemoveDevice_NotRegisteredInChatForAll {
            get {
                return ResourceManager.GetString("RemoveDevice_NotRegisteredInChatForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Device.
        /// </summary>
        internal static string SingleDeviceMode_Md2 {
            get {
                return ResourceManager.GetString("SingleDeviceMode_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group chat is already registered and active with name *{0}*. Meshtastic devices can reach it using `{3} {1}` command via {2} or private channel registered with TMesh. If you want to change group name, disable it with `{4}` command and start again with new name..
        /// </summary>
        internal static string Start_GroupAlreadyActive_Md1 {
            get {
                return ResourceManager.GetString("Start_GroupAlreadyActive_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat is group chat. Please provide a unique name for the chat. Name should have no spaces and contain less than {0} characters. Name can&apos;t start with &apos;@&apos;. Meshtastic devices will be able to connect to this chat with {2} &lt;your_chat_name&gt; command via {1} node or private channel registered with TMesh..
        /// </summary>
        internal static string Start_GroupNeedName {
            get {
                return ResourceManager.GetString("Start_GroupNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use chat features you need to set a Telegram username for your account in Telegram settings. Please set a username and then use {0} command again..
        /// </summary>
        internal static string Start_NeedUsername {
            get {
                return ResourceManager.GetString("Start_NeedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Your Telegram chat is now registered with TMesh\!
        ///
        ///🔹 Meshtastic devices and channels can now initiate a chat with you using:
        ///  `{4} {0}` via {1} or private channel registered with TMesh\.
        ///
        ///🔹 You can also start a chat with any Meshtastic device:
        ///  `{4} \!\&lt;deviceId\&gt;`
        ///  Example: `{4} \!75bcd15`
        ///
        ///🔹 To end an active chat session:
        ///  `{5}` \- ends current chat session
        ///🔹 To disable your chat from receiving new chat request from Meshtastic \(already approved devices and channels still will be able [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Start_PrivateDone_Md2 {
            get {
                return ResourceManager.GetString("Start_PrivateDone_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Chat session with {0} has been stopped.
        /// </summary>
        internal static string StopChat_Done {
            get {
                return ResourceManager.GetString("StopChat_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat session with Telegram chat has been stopped.
        /// </summary>
        internal static string StopChat_MeshNotification {
            get {
                return ResourceManager.GetString("StopChat_MeshNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0} is ended.
        /// </summary>
        internal static string StopChat_MeshOtherEndedNotification {
            get {
                return ResourceManager.GetString("StopChat_MeshOtherEndedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active chat session to stop..
        /// </summary>
        internal static string StopChat_NoActiveSession {
            get {
                return ResourceManager.GetString("StopChat_NoActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string TimestampAgo {
            get {
                return ResourceManager.GetString("TimestampAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string TimestampAgo_Md2 {
            get {
                return ResourceManager.GetString("TimestampAgo_Md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code format. Please send the 6-digit verification code sent to your Meshtastic device. Send {0} to cancel..
        /// </summary>
        internal static string VerificationCode_InvalidFormat {
            get {
                return ResourceManager.GetString("VerificationCode_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired code. Please check it and try again, or cancel with {0}..
        /// </summary>
        internal static string VerificationCode_InvalidOrExpired {
            get {
                return ResourceManager.GetString("VerificationCode_InvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful..
        /// </summary>
        internal static string VerificationCode_Success {
            get {
                return ResourceManager.GetString("VerificationCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMesh verification code is: {0}.
        /// </summary>
        internal static string VerificationCode_Text {
            get {
                return ResourceManager.GetString("VerificationCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the TMesh Telegram bot! This bot allows you to connect your Telegram account with Meshtastic devices and channels, enabling seamless communication between them.
        ///Please read carefully the privacy disclaimer:
        ///
        ///*{0}*
        ///
        ///Please reply with *{1}* to start using the bot or {2} to cancel..
        /// </summary>
        internal static string WelcomeMessage_Md1 {
            get {
                return ResourceManager.GetString("WelcomeMessage_Md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
