// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TBot.Analytics;

#nullable disable

namespace TBot.Migrations.Analytics
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20251218073253_AddIndex")]
    partial class AddIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TBot.Analytics.Models.DeviceMetric", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AccuracyMeters")
                        .HasColumnType("integer");

                    b.Property<float?>("AirUtil")
                        .HasColumnType("real");

                    b.Property<float?>("ChannelUtil")
                        .HasColumnType("real");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Instant>("LocationUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("DeviceId", "Timestamp");

                    b.HasIndex("Timestamp");

                    b.ToTable("DeviceMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
