// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TBot.Analytics;

#nullable disable

namespace TBot.Migrations.Analytics
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260501163101_NodeInfo")]
    partial class NodeInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TBot.Analytics.Models.DeviceMetric", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AccuracyMeters")
                        .HasColumnType("integer");

                    b.Property<float?>("AirUtil")
                        .HasColumnType("real");

                    b.Property<float?>("ChannelUtil")
                        .HasColumnType("real");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Instant>("LocationUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("DeviceId", "Timestamp");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NetworkId", "Timestamp");

                    b.ToTable("DeviceMetrics");
                });

            modelBuilder.Entity("TBot.Analytics.Models.LinkTrace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromGatewayId")
                        .HasColumnType("bigint");

                    b.Property<double>("FromLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("FromLongitude")
                        .HasColumnType("double precision");

                    b.Property<int>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("PacketId")
                        .HasColumnType("bigint");

                    b.Property<LocalDate>("RecDate")
                        .HasColumnType("date");

                    b.Property<byte?>("Step")
                        .HasColumnType("smallint");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ToGatewayId")
                        .HasColumnType("bigint");

                    b.Property<double>("ToLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("ToLongitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId", "RecDate");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("NetworkId", "RecDate"), new[] { "PacketId", "FromGatewayId", "ToGatewayId", "Step", "ToLatitude", "ToLongitude", "FromLatitude", "FromLongitude", "Timestamp" });

                    b.ToTable("Traces");
                });

            modelBuilder.Entity("TBot.Analytics.Models.NodeInfo", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HardwareModel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnmessagable")
                        .HasColumnType("boolean");

                    b.Property<string>("LongName")
                        .HasColumnType("text");

                    b.Property<long?>("MacAddr")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.ToTable("NodeInfos");
                });

            modelBuilder.Entity("TBot.Analytics.Models.Packet", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<byte>("Channel")
                        .HasColumnType("smallint");

                    b.Property<int?>("DecodedByPublicChannelId")
                        .HasColumnType("integer");

                    b.Property<long>("Dest")
                        .HasColumnType("bigint");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<long>("From")
                        .HasColumnType("bigint");

                    b.Property<long>("GatewayId")
                        .HasColumnType("bigint");

                    b.Property<byte>("HopLimit")
                        .HasColumnType("smallint");

                    b.Property<byte>("HopStart")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsEmoji")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTMeshGateway")
                        .HasColumnType("boolean");

                    b.Property<string>("MqttChannel")
                        .HasColumnType("text");

                    b.Property<bool>("NeedReplyFlag")
                        .HasColumnType("boolean");

                    b.Property<byte>("NextHop")
                        .HasColumnType("smallint");

                    b.Property<bool>("OkToMqttFlag")
                        .HasColumnType("boolean");

                    b.Property<long>("PacketId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PkiEncrypted")
                        .HasColumnType("boolean");

                    b.Property<int>("PortNum")
                        .HasColumnType("integer");

                    b.Property<byte>("Priority")
                        .HasColumnType("smallint");

                    b.Property<byte>("RelayNode")
                        .HasColumnType("smallint");

                    b.Property<long>("ReplyId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("RxRssi")
                        .HasColumnType("integer");

                    b.Property<float>("RxSnr")
                        .HasColumnType("real");

                    b.Property<long>("RxTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("Source")
                        .HasColumnType("bigint");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("To")
                        .HasColumnType("bigint");

                    b.Property<byte>("Transport")
                        .HasColumnType("smallint");

                    b.Property<long>("TxAfter")
                        .HasColumnType("bigint");

                    b.Property<bool>("ViaMqtt")
                        .HasColumnType("boolean");

                    b.Property<bool>("WantAck")
                        .HasColumnType("boolean");

                    b.Property<bool>("WantResponse")
                        .HasColumnType("boolean");

                    b.HasKey("RecordId");

                    b.HasIndex("PacketId");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("TBot.Analytics.Models.PacketBody", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("RecordId");

                    b.ToTable("RawPackets");
                });
#pragma warning restore 612, 618
        }
    }
}
